### PR TITLE
removed spinner-react, added pure css loader

### PR DESCRIPTION
**Pull request by aadarsh10c**
1) Removed the  spinners react library
2) Added the pure CSS Loader

### CODE REVIEW

**Comment by aadarsh10c** [comment]
Closes #1

**Comment by VikSil** [comment]
Hi @aadarsh10c 
Please place the spinner div directly into `Loading.jsx`. There is no need to introduce a new component.

**Comment by aadarsh10c** [comment]
@VikSil ,  I have removed the greenloading component.Let me knwo if u need anythin else.

**Comment by VikSil** [comment]
Reviewed and merged. Looks great. Thanks a lot for your contribution @aadarsh10c .

**Pull request merged**
